language: php
php:
  - 7.2
sudo: required

before_install:
  - sudo rm -rf ~/.nvm - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g npm

install:
  - npm install
  - composer install
  - cd docs
  - npm install

stages:
  - build
  - test
  - docs
  - release

jobs:
  include:
    - stage: build
      script:
      - npm run production

    - stage: test
      script: ./vendor/bin/phpunit

    - stage: docs
      script: ./docs/node_modules/vuepress build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_OAUTH_TOKEN
        keep-history: true
        on: 
          branch: master

    - stage: release
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          branch: master
          tags: true