language: php
php:
  - 7.1.3
sudo: required

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - docs/node_modules

before_install:
  - sudo rm -rf ~/.nvm - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
  - npm install
  - composer install
  - cd docs && npm install
  - cd ../
  - cp .env.travis .env
  - php artisan key:generate

stages:
  - build
  - test
  - docs
  - release

jobs:
  include:
    - stage: build
      script:
      - npm run production

    - stage: test
      script: ./vendor/bin/phpunit

    - stage: docs
      script: 
      - cd ./docs
      - ./docs/node_modules/.bin/vuepress build
      - cd ../
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_OAUTH_TOKEN
        keep-history: true
        on: 
          branch: master

    - stage: release
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          branch: master
          tags: true